# Generated by Django 4.2.5 on 2023-09-18 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='N°')),
                ('municipio', models.CharField(choices=[('Selvíria', 'Selvíria'), ('Inocência', 'Inocência')], max_length=50, verbose_name='Município')),
                ('uf', models.CharField(choices=[('MS', 'MS'), ('MT', 'MT'), ('SP', 'SP'), ('RJ', 'RJ')], max_length=2)),
                ('data_inicial', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('data_div_ativa', models.DateField(blank=True, null=True)),
                ('valor_atributo', models.CharField(blank=True, max_length=14, null=True)),
                ('valor_multa', models.CharField(blank=True, max_length=14, null=True)),
                ('valor_credito', models.CharField(blank=True, max_length=14, null=True)),
                ('valor_atualizado', models.CharField(blank=True, max_length=14, null=True)),
                ('data_valor_atualizado', models.DateField(blank=True, null=True)),
                ('nome_contribuinte', models.CharField(max_length=50)),
                ('tipo_pessoa', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], max_length=50)),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('nome_fantasia', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(max_length=150)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio_contribuinte', models.CharField(blank=True, max_length=50, null=True)),
                ('uf_contribuinte', models.CharField(blank=True, choices=[('MS', 'MS'), ('MT', 'MT'), ('SP', 'SP'), ('RJ', 'RJ')], max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('criador_processo_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
