# Generated by Django 4.2.3 on 2023-10-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='id_novo_registro',
            new_name='id_registro',
        ),
    ]
