# Generated by Django 4.2.5 on 2023-09-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndamentoAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data_andamento', models.DateField(verbose_name='Data do Andamento')),
                ('andamento', models.CharField(choices=[('Abertura', 'Abertura'), ('Parecer Fiscal', 'Parecer Fiscal'), ('Decisão 1ª Instância', 'Decisão 1ª Instância'), ('Suspenso Para Fiscalização Futura', 'Suspenso Para Fiscalização Futura'), ('Auto de Infração e Termo de Intimação - AITI.', 'Auto de Infração e Termo de Intimação - AITI.'), ('Termo de Intimação Fiscal - TIF.-tif.', 'Termo de Intimação Fiscal - TIF.'), ('Decisão de 2ª Instância', 'Decisão de 2ª Instância'), ('Cobrança de Documentação', 'Cobrança de Documentação'), ('Recurso Voluntário', 'Recurso Voluntário'), ('Fim do Contrato com a Assessoria', 'Fim do Contrato com a Assessoria'), ('Manifestação', 'Manifestação'), ('Recebimento do AR', 'Recebimento do AR'), ('Despacho', 'Despacho'), ('Aguardando Pagamento', 'Aguardando Pagamento'), ('Apresentação de Documentação para Análise', 'Apresentação de Documentação para Análise'), ('Aguardando AR', 'Aguardando AR'), ('Ofício', 'Ofício'), ('Revelia', 'Revelia'), ('Execução', 'Execução'), ('Confissão de Dívida (Parcelamento)', 'Confissão de Dívida (Parcelamento)'), ('Reenvio de Documento', 'Reenvio de Documento'), ('Parecer Juridico', 'Parecer Juridico'), ('Certidão', 'Certidão'), ('Encaminhado', 'Encaminhado')], max_length=100, verbose_name='Andamento')),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('data_prazo', models.DateField(blank=True, null=True)),
                ('funcionario', models.CharField(blank=True, max_length=50, null=True)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
                ('arquivo_1', models.FileField(blank=True, upload_to='uploads/', verbose_name='Arquivo')),
                ('arquivo_2', models.FileField(blank=True, upload_to='uploads/', verbose_name='Arquivo')),
                ('arquivo_3', models.FileField(blank=True, upload_to='uploads/', verbose_name='Arquivo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.processoadm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
