# Generated by Django 4.2.5 on 2023-10-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamentoadm',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='processoadm',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='tipoandamentoadm',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
