# Generated by Django 4.2.3 on 2023-09-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoAndamento',
            new_name='TipoAndamentoAdm',
        ),
    ]
