# Generated by Django 4.2.5 on 2023-09-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamentoadm',
            name='arquivo_1',
            field=models.FileField(blank=True, upload_to='Arquivo/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='andamentoadm',
            name='arquivo_2',
            field=models.FileField(blank=True, upload_to='Arquivo/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='andamentoadm',
            name='arquivo_3',
            field=models.FileField(blank=True, upload_to='Arquivo/', verbose_name='Arquivo'),
        ),
    ]
