# Generated by Django 4.2.5 on 2023-10-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='id_registro',
            new_name='objeto_id',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='alteracoes',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='campos_alterados',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
