# Generated by Django 4.2.5 on 2023-09-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andamentoadm',
            old_name='total_valor_pago',
            new_name='valor_pago',
        ),
    ]
