# Generated by Django 4.2.5 on 2023-09-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_rename_total_valor_pago_andamentoadm_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamentoadm',
            name='situacao_pagamento',
            field=models.CharField(blank=True, choices=[('Sem Pagamento', 'Sem Pagamento'), ('Com Pagamento', 'Com Pagamento')], max_length=100, null=True),
        ),
    ]
