# Generated by Django 4.2.5 on 2023-10-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_rename_id_registro_auditoria_objeto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamentoadm',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='andamentoadm',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='processoadm',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='tipoandamentoadm',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
