# Generated by Django 4.2.5 on 2023-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_rename_tipoandamento_tipoandamentoadm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andamentoadm',
            old_name='andamento',
            new_name='andamento_adm',
        ),
        migrations.AlterField(
            model_name='tipoandamentoadm',
            name='andamento',
            field=models.CharField(max_length=100, verbose_name='Tipo de Andamento'),
        ),
    ]
