# Generated by Django 4.2.5 on 2023-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_remove_andamentoadm_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadm',
            name='municipio',
            field=models.CharField(max_length=50, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='processoadm',
            name='uf',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='processoadm',
            name='uf_contribuinte',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
