# Generated by Django 4.2.5 on 2023-10-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_andamentoadm_checkbox_alter_andamentoadm_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamentoadm',
            name='checkbox',
        ),
    ]
