# Generated by Django 4.2.5 on 2023-10-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_remove_andamentoadm_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamentoadm',
            name='tipo_andamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processo.tipoandamentoadm'),
        ),
    ]
