# Generated by Django 4.2.5 on 2023-09-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_alter_andamentoadm_arquivo_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andamentoadm',
            old_name='arquivo_1',
            new_name='arquivo',
        ),
        migrations.RemoveField(
            model_name='andamentoadm',
            name='arquivo_2',
        ),
        migrations.RemoveField(
            model_name='andamentoadm',
            name='arquivo_3',
        ),
    ]
