# Generated by Django 4.2.5 on 2023-10-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0006_auditoria_objeto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='objeto_descricao',
            new_name='objeto_excluido',
        ),
    ]
